services:
    endroid.image_placeholder.service:
        class: Endroid\ImagePlaceholderBundle\Service\ImagePlaceholderService

    endroid.image_placeholder.twig.extension:
        class: Endroid\ImagePlaceholderBundle\Twig\Extension\ImagePlaceholderExtension
        arguments: [ '@endroid.image_placeholder.service' ]
        tags:
            - { name: twig.extension }

    endroid.image_placeholder.provider.baconmockup:
        class: Endroid\ImagePlaceholderBundle\Provider\BaconMockupProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.beerhold:
        class: Endroid\ImagePlaceholderBundle\Provider\BeerHoldProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.loremflickr:
        class: Endroid\ImagePlaceholderBundle\Provider\LoremFlickrProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.lorempixel:
        class: Endroid\ImagePlaceholderBundle\Provider\LoremPixelProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.pipsum:
        class: Endroid\ImagePlaceholderBundle\Provider\PipsumProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.placebear:
        class: Endroid\ImagePlaceholderBundle\Provider\PlaceBearProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.placecreature:
        class: Endroid\ImagePlaceholderBundle\Provider\PlaceCreatureProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.placehoff:
        class: Endroid\ImagePlaceholderBundle\Provider\PlaceHoffProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.placehold:
        class: Endroid\ImagePlaceholderBundle\Provider\PlaceholdItProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.placekitten:
        class: Endroid\ImagePlaceholderBundle\Provider\PlaceKittenProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.placeskull:
        class: Endroid\ImagePlaceholderBundle\Provider\PlaceSkullProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.unsplash:
        class: Endroid\ImagePlaceholderBundle\Provider\UnsplashItProvider
        tags:
            - { name: endroid.image_placeholder.provider }