services:
    endroid.image_placeholder.service:
        class: Endroid\Bundle\ImagePlaceholderBundle\Service\ImagePlaceholderService

    endroid.image_placeholder.twig.extension:
        class: Endroid\Bundle\ImagePlaceholderBundle\Twig\Extension\ImagePlaceholderExtension
        arguments: [@endroid.image_placeholder.service]
        tags:
            - { name: twig.extension }

    endroid.image_placeholder.provider.placehold:
        class: Endroid\Bundle\ImagePlaceholderBundle\Provider\PlaceholdItProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.placekitten:
        class: Endroid\Bundle\ImagePlaceholderBundle\Provider\PlaceKittenProvider
        tags:
            - { name: endroid.image_placeholder.provider }

    endroid.image_placeholder.provider.unsplash:
        class: Endroid\Bundle\ImagePlaceholderBundle\Provider\UnsplashItProvider
        tags:
            - { name: endroid.image_placeholder.provider }
